# Use the official Node.js image
FROM node:20

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install --verbose

# Copy the rest of the application
COPY . .

# Build the React app
RUN npm run build

# Expose port 3000 for the server
EXPOSE 3000

# Run the development server
CMD ["npm", "run", "dev"]
